/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.fatec.Farmacia.view;

import br.com.fatec.Farmacia.DAO.ClienteDAO;
import br.com.fatec.Farmacia.Exceptions.DadosBrancoException;
import br.com.fatec.Farmacia.bean.Cliente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author nicol
 */
public class ClienteView extends javax.swing.JFrame {

    //variaveis auxiliares
    private Cliente clienteBean = new Cliente();
    private ClienteDAO dao = new ClienteDAO();

    /**
     * Creates new form ClienteView
     */
    public ClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        lblCelular = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtCel = new javax.swing.JTextField();
        txtCpf = new javax.swing.JTextField();
        lblCPF = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));

        lblID.setBackground(new java.awt.Color(255, 0, 255));
        lblID.setText("ID");

        txtID.setEditable(false);
        txtID.setBackground(new java.awt.Color(153, 153, 153));
        txtID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Nome");

        lblTelefone.setText("Telefone");

        lblCelular.setText("Celular");

        lblEmail.setText("Email");

        lblCPF.setText("CPF");

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastro de Clientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblID)
                                .addGap(18, 18, 18)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNome)
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail)
                                    .addComponent(lblCPF))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCpf)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblTelefone)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCelular)
                                        .addGap(27, 27, 27)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtCel)
                                    .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInserir)
                .addGap(18, 18, 18)
                .addComponent(btnAlterar)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblID)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCPF)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTelefone)
                            .addComponent(txtTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCelular)
                            .addComponent(txtCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnCancelar))
                .addGap(35, 35, 35))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mensagem(String texto) {
        JOptionPane.showMessageDialog(rootPane,
                texto,
                "Informação ao Usuário",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * Mostra uma mensagem de erro na tela
     *
     * @param erro
     */
    private void erro(String erro) {
        JOptionPane.showMessageDialog(rootPane,
                erro,
                "Informação ao Usuário",
                JOptionPane.ERROR_MESSAGE);

    }

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed

        try {
            //id com auto increment, mas ainda é passado ao cliente
            //se preenchido dados sem codCliente
            /*clienteBean.setTelefone("TESTANDO MACAXEIRA");
            mensagem("Olha: "+ clienteBean.getTelefone());
            return;
             */
            
            moveTelaParaBean();
            if (dao.insere(clienteBean)) {
                mensagem("Dados Incluidos com Sucesso");
                limpaCampos();
                txtNome.requestFocus();
            } else {
                erro("Inclusão não foi bem sucedida");
            }
        } catch (DadosBrancoException ex) {
            erro(ex.getMessage());
            //return;
        } catch (SQLException ex) {
            erro(ex.getMessage());
        }

    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        
        try {
            moveTelaParaBeanPesquisar();
            clienteBean = dao.buscaID(clienteBean);
            if (clienteBean == null) {
                erro("Dados não encontrados!");
            } else {
                moveBeanParaTela();
            }
        } catch (SQLException ex) {
            erro(ex.getMessage());
        } catch (DadosBrancoException ex) {
             erro(ex.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        try {
            // TODO add your handling code here:
            moveTelaParaBean();
            if (dao.altera(clienteBean)) {
                mensagem("Dados alterados com sucesso!");
                limpaCampos();
                txtNome.requestFocus();
            } else {
                erro("Alteração não foi bem sucedida");
            }
        } catch (SQLException ex) {
            erro(ex.getMessage());
        } catch (DadosBrancoException ex) {
            erro(ex.getMessage());
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        try {
            // TODO add your handling code here:
            moveTelaParaBean();
            int resp = JOptionPane.showConfirmDialog(rootPane, "Tem certeza que deseja excluir os dados"
                    + " do cliente " + clienteBean.getNome() + " ?",
                    "Confirmar Exclusão",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if (resp == JOptionPane.NO_OPTION) {
                return;
            }
            if (dao.remove(clienteBean)) {
                mensagem("Dados excluídos com sucesso!");
                limpaCampos();
                txtNome.requestFocus();
            } else {
                erro("Dados não foram excluídos com sucesso");
            }
        } catch (SQLException ex) {
            erro(ex.getMessage());
        } catch (DadosBrancoException ex) {
            erro(ex.getMessage());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void limpaCampos() {
        txtID.setText("");
        txtCpf.setText("");
        txtNome.setText("");
        txtEmail.setText("");
        txtTel.setText("");
        txtCel.setText("");
    }
/*
    private boolean verificaBrancoInsere() {
        return !txtID.getText().isEmpty()
                || !txtID.getText().isEmpty() || !txtID.getText().isEmpty() || !txtID.getText().isEmpty()
                || !txtID.getText().isEmpty();
    }

    private void moveTelaParaBeanInsere() throws DadosBrancoException {
        if (verificaBrancoInsere()) {
            clienteBean = new Cliente();
            clienteBean.setCelular(txtCel.getText());
            clienteBean.setTelefone(txtTel.getText());
            clienteBean.setIdCliente(Integer.parseInt(txtID.getText()));
            clienteBean.setEmail(txtEmail.getText());
            clienteBean.setCpf(txtCpf.getText());
            clienteBean.setNome(txtNome.getText());
            /*mensagem("ID: " + clienteBean.getIdCliente() + 
                "Nome: " + clienteBean.getNome() +
                "CPF: " + clienteBean.getCpf() +
                "Tel: " + clienteBean.getTelefone());//****/////*
        /*} else {
            throw new DadosBrancoException("Preencha todos os campos!");
        }
    }*/

    private boolean verificaBranco() {
        return !txtID.getText().isEmpty() || !txtCpf.getText().isEmpty()
                || !txtNome.getText().isEmpty() || !txtEmail.getText().isEmpty() || !txtTel.getText().isEmpty()
                || !txtCel.getText().isEmpty();
    }

    private void moveTelaParaBean() throws DadosBrancoException {
        if (verificaBranco()) {
            clienteBean = new Cliente();
            clienteBean.setCelular(txtCel.getText());
            clienteBean.setTelefone(txtTel.getText());
            if(txtID.getText().isEmpty())
                clienteBean.setIdCliente(0); //autoincremento
            else
                clienteBean.setIdCliente(Integer.parseInt(txtID.getText()));
            clienteBean.setEmail(txtEmail.getText());
            clienteBean.setCpf(txtCpf.getText());
            clienteBean.setNome(txtNome.getText());
        } else {
            throw new DadosBrancoException("Preencha todos os campos!");
        }
    }
    private void moveTelaParaBeanPesquisar () throws DadosBrancoException {
        if(!txtCpf.getText().isEmpty()){
            clienteBean = new Cliente();
            clienteBean.setCelular(txtCel.getText());
            clienteBean.setTelefone(txtTel.getText());
            if(txtID.getText().isEmpty())
                clienteBean.setIdCliente(0); //autoincremento
            else
                clienteBean.setIdCliente(Integer.parseInt(txtID.getText()));
            clienteBean.setEmail(txtEmail.getText());
            clienteBean.setCpf(txtCpf.getText());
            clienteBean.setNome(txtNome.getText());
        } else {
            throw new DadosBrancoException("Preencha o CPF!");
        }
    }

    private void moveBeanParaTela() {
        txtCel.setText(clienteBean.getCelular());
        txtTel.setText(clienteBean.getTelefone());
        txtID.setText(Integer.toString(clienteBean.getIdCliente()));
        txtEmail.setText(clienteBean.getEmail());
        txtCpf.setText(clienteBean.getCpf());
        txtNome.setText(clienteBean.getNome());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCelular;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JTextField txtCel;
    private javax.swing.JTextField txtCpf;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTel;
    // End of variables declaration//GEN-END:variables
}
